language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - pypy


virtualenv:
  system_site_packages: true

before_script:
  - source test.env

install:
  - export PYTHONIOENCODING=UTF8
  - python setup.py install

script:
  - ./tools/testall.py
