language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - pypy

before_install:
  - sudo apt-get install python-yaml python3-yaml
install:
  - export PYTHONIOENCODING=UTF8
  - pip install coveralls pytest-cov ptyprocess

script:
    - ./tools/display-sighandlers.py
    - ./tools/display-terminalinfo.py
    - py.test --cov pexpect --cov-config .coveragerc

after_success:
  - coverage combine
  - coveralls
