language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

virtualenv:
  system_site_packages: true

before_script:
  - source test.env

install:
  - export PYTHONIOENCODING=UTF8
  - python setup.py install
  - pip install coveralls --use-mirrors

script:
  - ./tools/testall.py

after_success:
  coveralls
